name: Build and Deploy Documentation

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . --config-settings editable_mode=compat
          pip install -r sphinx-doc/requirements.txt

      - name: Build Documentation
        run: |
          cd sphinx-doc
          make html

      - name: Upload Documentation as Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: sphinx-doc/_build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
